#! /usr/bin/env python

#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 3 of the License, or
#       (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc.

import glob
import optparse
import os
import shutil
import sys
import tempfile

import Djvubind.utils
import Djvubind.organizer

if __name__ == '__main__':
    # Command line parsing
    usage = "usage: %prog [options] directory"
    description = "djvubind is designed to facilitate creating high-quality djvu files, including positional ocr, metadata, and bookmarks."
    parser = optparse.OptionParser(usage, version='0.0.1', description=description)
    parser.set_defaults(quiet=False,
                        cover_front='cover_front.jpg', cover_back='cover_back.jpg',
                        metadata='metadata', bookmarks='bookmarks',
                        dpi=None)
    parser.add_option("--cover_front", dest="cover_front", help="Specifies an alternate front cover image.  By default, '%default' is used if present.")
    parser.add_option("--cover_back", dest="cover_back", help="Specifies an alternate back cover image.  By default, '%default' is used if present.")
    parser.add_option("--metadata", dest="metadata", help="Specifies an alternate metadata file.  By default, '%default' is used if present.")
    parser.add_option("--bookmarks", dest="bookmarks", help="Specifies an alternate bookmarks.  By default, '%default' is used if present.")
    parser.add_option("--dpi", dest="dpi", help="The dpi of the images.  Presently this *needs* to be specified by hand.")
    parser.add_option("-q", "--quiet", action="store_true", dest="quiet")
    (options, args) = parser.parse_args(sys.argv)

    if options.quiet:
        sys.stdout = open('/dev/null', 'w')

    if options.dpi is None:
        print('Presently, the --dpi option *must* be sepcified.', file=sys.stderr)
        sys.exit(1)

    # Dependency check
    deps = ['cpaldjvu', 'djvm', 'djvused', 'identify', 'minidjvu', 'tesseract']
    for dep in deps:
        if (not Djvubind.utils.is_executable(dep)):
            print('err: __main__: external dependency ({0}) cannot be found'.format(dep), file=sys.stderr)
            sys.exit(1)

    # Change working directory if necessary
    if (len(args) > 2):
        print('Too many arguments, check your syntax.', file=sys.stderr)
        sys.exit(1)
    if (len(args) == 2):
        if (not os.path.isdir(args[1])):
            print('The argument ({0}) is not a directory.'.format(args[1]))
            sys.exit(1)
        else:
            directory = os.path.normpath(os.path.join(os.path.curdir, args[1]))
            os.chdir(directory)

    # Create list of all images going into the djvu file.
    book = Djvubind.organizer.Book()
    for file in Djvubind.utils.list_files():
        ext = file.split('.')[-1]
        ext = ext.lower()
        if (ext in ['tif', 'tiff', 'jpg', 'jpeg']) and (file not in [options.cover_front, options.cover_back]):
            book.insert_page(file)

    # Create djvu of bitonals with minidjvu
    temp_dir = tempfile.mkdtemp(dir='./', prefix='temp_')
    for page in book.pages:
        if page.bitonal:
            shutil.move(page.path, temp_dir)
    os.chdir(temp_dir)
    Djvubind.utils.execute('minidjvu --dpi {0} --pages-per-dict 100 * book.djvu'.format(options.dpi))
    for filename in glob.glob('*'):
        shutil.move(filename, '../')
    os.chdir('../')
    shutil.rmtree(temp_dir)

    # Create djvu of non-bitonals and insert into djvu
    for page in book.pages:
        if not page.bitonal:
            Djvubind.utils.execute('convert "{0}" "{0}.ppm"'.format(page.path))
            Djvubind.utils.execute('cpaldjvu -dpi {0} "{1}.ppm" "{1}.djvu"'.format(page.dpi, page.path))
            os.remove('{0}.ppm'.format(page.path))
            page_number = book.pages.index(page)
            Djvubind.utils.execute('djvm -i book.djvu "{0}.djvu" {1}'.format(page.path, page_number+1))
            os.remove('{0}.djvu'.format(page.path))

    # Ocr
    #os.system('djvuocr -i "." -f book.djvu')

    # Insert front/back covers, metadata, and bookmarks
    if os.path.isfile(options.cover_front):
        Djvubind.utils.execute('c44 -dpi {0} "{1}" "{1}.djvu"'.format(options.dpi, options.cover_front))
        Djvubind.utils.execute('djvm -i book.djvu "{0}.djvu" 1'.format(options.cover_front))
        os.remove('{0}.djvu'.format(options.cover_front))
    if os.path.isfile(options.cover_back):
        Djvubind.utils.execute('c44 -dpi {0} "{1}" "{1}.djvu"'.format(options.dpi, options.cover_back))
        Djvubind.utils.execute('djvm -i book.djvu "{0}.djvu" -1'.format(options.cover_back))
        os.remove('{0}.djvu'.format(options.cover_back))
    if os.path.isfile(options.metadata):
        Djvubind.utils.execute('djvused -e "set-meta {0}; save" book.djvu'.format(options.metadata))
    if os.path.isfile(options.bookmarks):
        Djvubind.utils.execute('djvused -e "set-outline {0}; save" book.djvu'.format(options.bookmarks))
